### ISSUE TITLE
Articles redirecting to John Stewart

### ISSUE THREAD

**Issue by lexxal** [thetriangle/wc#46]
Look into: http://thetriangle.org/news/32583/

**Comment by thenoelforte** [comment]
Nailed down the source of this issue. Essentially the media attachment pages for some posts are taking precedence over articles that have a permalink that starts with news. In this case, the title for the John Stewart photo was appropriately titled "news.jpg" and now exists at `thetriangle.org/news`. I'm going to look into adjusting the URL structure now. We may in the future want to adjust the URL's so they're a bit more specific rather than `/news/title-of-article/`.

Thoughts @NicolenaStiles?

**Comment by thenoelforte** [comment]
Issue is fixed for now. I would also *STRONGLY* consider renaming these as well.
![screen shot 2016-06-01 at 10 46 38 pm](https://cloud.githubusercontent.com/assets/2560683/15732409/ce962f02-284a-11e6-99b8-f88b40a5b666.PNG)
![screen shot 2016-06-01 at 10 47 02 pm](https://cloud.githubusercontent.com/assets/2560683/15732412/d0089172-284a-11e6-9ed5-0936f483c72b.PNG)
